# Generated by Django 3.0 on 2020-02-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200211_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
    ]
